import dihydration1 from '././../assets/dihydration/dihydration1.jpg'
import dihydration2 from '././../assets/dihydration/dihydration2.jpg'
import dihydration3 from '././../assets/dihydration/dihydration3.jpg'
import dihydration4 from '././../assets/dihydration/dihydration4.jpg'
import dihydration5 from '././../assets/dihydration/dihydration5.jpg'
import dihydration6 from '././../assets/dihydration/dihydration6.jpg'
import dihydration7 from '././../assets/dihydration/dihydration7.jpg'
import dihydration8 from '././../assets/dihydration/dihydration8.jpg'
import dihydration9 from '././../assets/dihydration/dihydration9.jpg'
import dihydration10 from '././../assets/dihydration/dihydration10.jpg'
import dihydration11 from '././../assets/dihydration/dihydration11.jpg'
import dihydration12 from '././../assets/dihydration/dihydration12.jpg'
import dihydration13 from '././../assets/dihydration/dihydration13.jpg'
import dihydration14 from '././../assets/dihydration/dihydration14.jpg'
import dihydration15 from '././../assets/dihydration/dihydration15.jpg'
import dihydration16 from '././../assets/dihydration/dihydration16.jpg'
import dihydration17 from '././../assets/dihydration/dihydration17.jpg'
import dihydration18 from '././../assets/dihydration/dihydration18.jpg'
import dihydration19 from '././../assets/dihydration/dihydration19.jpg'
import dihydration20 from '././../assets/dihydration/dihydration20.jpg'
import dihydration21 from '././../assets/dihydration/dihydration21.jpg'
import dihydration22 from '././../assets/dihydration/dihydration22.jpg'
import dihydration23 from '././../assets/dihydration/dihydration23.jpg'
import dihydration24 from '././../assets/dihydration/dihydration24.jpg'


export const DihydrationData = [
    {id: 0, url: dihydration1},
    {id: 1, url: dihydration2},
    {id: 2, url: dihydration3},
    {id: 3, url: dihydration4},
    {id: 4, url: dihydration5},
    {id: 5, url: dihydration6},
    {id: 6, url: dihydration7},
    {id: 7, url: dihydration8},
    {id: 8, url: dihydration9},
    {id: 9, url: dihydration10},
    {id: 10, url: dihydration11},
    {id: 11, url: dihydration12},
    {id: 12, url: dihydration13},
    {id: 13, url: dihydration14},
    {id: 14, url: dihydration15},
    {id: 15, url: dihydration16},
    {id: 16, url: dihydration17},
    {id: 17, url: dihydration18},
    {id: 18, url: dihydration19},
    {id: 19, url: dihydration20},
    {id: 20, url: dihydration21},
    {id: 21, url: dihydration22},
    {id: 22, url: dihydration23},
    {id: 23, url: dihydration24},
]