import groundcover1 from '././../assets/groundcover/groundcover1.jpg'
import groundcover2 from '././../assets/groundcover/groundcover2.jpg'
import groundcover3 from '././../assets/groundcover/groundcover3.jpg'
import groundcover4 from '././../assets/groundcover/groundcover4.jpg'
import groundcover5 from '././../assets/groundcover/groundcover5.jpg'
import groundcover6 from '././../assets/groundcover/groundcover6.jpg'
import groundcover7 from '././../assets/groundcover/groundcover7.jpg'
import groundcover8 from '././../assets/groundcover/groundcover8.jpg'
import groundcover9 from '././../assets/groundcover/groundcover9.jpg'
import groundcover10 from '././../assets/groundcover/groundcover10.jpg'
import groundcover11 from '././../assets/groundcover/groundcover11.jpg'
import groundcover12 from '././../assets/groundcover/groundcover12.jpg'
import groundcover13 from '././../assets/groundcover/groundcover13.jpg'
import groundcover14 from '././../assets/groundcover/groundcover14.jpg'
import groundcover15 from '././../assets/groundcover/groundcover15.jpg'
import groundcover16 from '././../assets/groundcover/groundcover16.jpg'
import groundcover17 from '././../assets/groundcover/groundcover17.jpg'
import groundcover18 from '././../assets/groundcover/groundcover18.jpg'
import groundcover19 from '././../assets/groundcover/groundcover19.jpg'
import groundcover20 from '././../assets/groundcover/groundcover20.jpg'
import groundcover21 from '././../assets/groundcover/groundcover21.jpg'
import groundcover22 from '././../assets/groundcover/groundcover22.jpg'
import groundcover23 from '././../assets/groundcover/groundcover23.jpg'
import groundcover24 from '././../assets/groundcover/groundcover24.jpg'
import groundcover25 from '././../assets/groundcover/groundcover25.jpg'
import groundcover26 from '././../assets/groundcover/groundcover26.jpg'
import groundcover27 from '././../assets/groundcover/groundcover27.jpg'
import groundcover28 from '././../assets/groundcover/groundcover28.jpg'
import groundcover29 from '././../assets/groundcover/groundcover29.jpg'
import groundcover30 from '././../assets/groundcover/groundcover30.jpg'

export const GroundCoverData = [
    {id: 0, url: groundcover1},
    {id: 1, url: groundcover2},
    {id: 2, url: groundcover3},
    {id: 3, url: groundcover4},
    {id: 4, url: groundcover5},
    {id: 5, url: groundcover6},
    {id: 6, url: groundcover7},
    {id: 7, url: groundcover8},
    {id: 8, url: groundcover9},
    {id: 9, url: groundcover10},
    {id: 10, url: groundcover11},
    {id: 11, url: groundcover12},
    {id: 12, url: groundcover13},
    {id: 13, url: groundcover14},
    {id: 14, url: groundcover15},
    {id: 15, url: groundcover16},
    {id: 16, url: groundcover17},
    {id: 17, url: groundcover18},
    {id: 18, url: groundcover19},
    {id: 19, url: groundcover20},
    {id: 20, url: groundcover21},
    {id: 21, url: groundcover22},
    {id: 22, url: groundcover23},
    {id: 23, url: groundcover24},
    {id: 24, url: groundcover25},
    {id: 25, url: groundcover26},
    {id: 26, url: groundcover27},
    {id: 27, url: groundcover28},
    {id: 28, url: groundcover29},
    {id: 29, url: groundcover30},
]